# Generated by Django 3.2.2 on 2021-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_meetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
