# Generated by Django 3.2.2 on 2021-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_alter_advisor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='url',
            field=models.URLField(max_length=10000),
        ),
    ]
